image: node:20

pipelines:
  branches:
    default:
      - step:
          name: Instalar dependencias
          caches:
            - node
          script:
            - corepack enable
            - corepack prepare yarn@4.12.0 --activate
            - yarn --version
            - yarn install --immutable

    develop:
      - step:
          name: Instalar dependencias
          caches:
            - node
          script:
            - corepack enable
            - corepack prepare yarn@4.12.0 --activate
            - yarn --version
            - yarn install --immutable

      - step:
          name: Revisar C�digo (Linting)
          caches:
            - node
          script:
            - corepack enable
            - corepack prepare yarn@4.12.0 --activate
            - yarn --version
            - yarn install --immutable
            - yarn lint
      - step:
          name: E2E (Playwright)
          image: mcr.microsoft.com/playwright:v1.55.0-jammy
          caches:
            - node
          script:
            - corepack enable
            - corepack prepare yarn@4.12.0 --activate
            - yarn --version
            - yarn install --immutable

            - npx playwright install chromium            
            - yarn start:e2e &
            
            - for i in {1..60}; do curl -sSf http://localhost:4200 >/dev/null && break || sleep 2; done
            - curl -sSf http://localhost:4200 >/dev/null

            - export PLAYWRIGHT_BASE_URL="http://localhost:4200"
            - npx playwright test --reporter=line

          artifacts:
            - test-results/**
            - playwright-report/**

    master:
      - step:
          name: Instalar dependencias
          caches:
            - node
          script:
            - corepack enable
            - corepack prepare yarn@4.12.0 --activate
            - yarn --version
            - rm -rf node_modules
            - yarn cache clean
            - yarn install --immutable

      - step:
          name: Construir SSR
          caches:
            - node
          script:
            - corepack enable
            - corepack prepare yarn@4.12.0 --activate
            - yarn --version
            - yarn install --immutable
            - yarn build-to-deploy:ssr
          artifacts:
            - dist/**
            - serverless.yml
            - lambda.js
            - package.json
            - node_modules/**

      - step:
          name: Desplegar en AWS usando SLS
          caches:
            - node
          script:
            - corepack enable
            - corepack prepare yarn@4.12.0 --activate
            - yarn --version
            - echo "Exportando variables de AWS..."
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_REGION=$AWS_REGION
            - echo "Desplegando con Serverless..."
            - npx serverless deploy --stage production

