export enum RolesEnum {
  PREREGISTER_USER = 'PREREGISTER_USER',
  AGENCY_OWNER = 'AGENCY_OWNER',
  INDEPENDANT_BROKER = 'INDEPENDANT_BROKER',
  AGENCY_BROKER = 'AGENCY_BROKER',
  AGENCY_ADMINISTRATOR = 'AGENCY_ADMINISTRATOR',
  PREREGISTER_INSURED = 'PREREGISTER_INSURED',
  INSURED = 'INSURED',
  ADMIN = 'ADMIN',
}

export enum CompleteRegisterRolesEnum {
  AGENCY_OWNER = RolesEnum.AGENCY_OWNER,
  INDEPENDANT_BROKER = RolesEnum.INDEPENDANT_BROKER,
}

export enum NewBrokerRolesEnum {
  AGENCY_BROKER = RolesEnum.AGENCY_BROKER,
  AGENCY_ADMINISTRATOR = RolesEnum.AGENCY_ADMINISTRATOR,
}

export enum AgencyBrokerRolesEnum {
  AGENCY_BROKER = RolesEnum.AGENCY_BROKER,
  AGENCY_ADMINISTRATOR = RolesEnum.AGENCY_ADMINISTRATOR,
  AGENCY_OWNER = RolesEnum.AGENCY_OWNER,
}
